[project]
name = "whybzz"
version = "0.1.0"
python = "3.8.7"
authors = [
    "Pallav Saxena <pallav.sdsaxena2638@gmail.com>"
]
repository = "https://github.com/paxF3E/whybzz"
description = "A basic discord music bot for personal use."
